# Generated by Django 3.2.8 on 2021-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_account', '0005_auto_20211014_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
